In [2]:
import math
import random #used for the random choice of a strategy
import sys
import numpy as np
import time
from collections import defaultdict

In [3]:
beta = 1
nbCh = 2
Q = defaultdict(int)
S_t = 1


r = np.random.random()

Z = sum(np.exp(beta*Q[(S_t, a)]) for a in range(nbCh))

print(Z)

cum_probas = np.zeros(nbCh+1)
cum_probas[1:] = np.array([np.exp(beta*Q[(S_t, a)])/Z for a in range(nbCh)]).cumsum()

draw = -1


for i in range(nbCh+1):
    if cum_probas[i] < r <= cum_probas[i+1]:
        draw = i
        break
print(draw)

2.0
1


In [4]:
np.concatenate((np.zeros(1), np.ones(3)))

array([ 0.,  1.,  1.,  1.])

In [5]:
import csv
 
myData = [["first_name", "second_name", "Grade"],
          ['Alex', 'Brian', 1],
          ['Tom']]
 
with open('example2.csv', 'w') as f:
    csv.writer(f).writerows(myData)
     
print("Writing complete")

Writing complete


In [6]:
def truncate(f):
    return float(format(f, '.2f').rstrip('0').rstrip('.'))

float(truncate(47.560000000000002))

47.56

In [7]:
import csv

Q = defaultdict(int)

Q[('0107', 0)] = 10
Q[('0107', 1)] = 11

Q[('1110', 0)] = 1
Q[('1110', 1)] = 2

Q[('1117', 0)] = 3
Q[('1117', 1)] = 4

Q[('0000', 0)] = 5
Q[('0000', 1)] = 6

Q[('0007', 0)] = 7
Q[('0007', 1)] = 8

In [8]:
nbCh = 2


from collections import OrderedDict

keys = list(OrderedDict.fromkeys(['1110', '1117', '0000', '0007']+[state for state, _ in Q.keys()]))

with open('dict.csv', 'w') as f:
    writer = csv.writer(f)
    writer.writerow(["State", "Wall follower", "Guidance"])
    for key in keys:
        writer.writerow([key]+ [Q[(key, i)] for i in range(nbCh)])

In [9]:
'1524751549'[3:]

'4751549'

In [10]:
trialDuration = np.ones(30)
trialDuration[-10:]

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [11]:
'/home/viki/catkin_ws/src/navigation_strategies/'+str(int(30333.33333))[3:]+'_Stats_'

'/home/viki/catkin_ws/src/navigation_strategies/33_Stats_'

In [15]:
Q = defaultdict(int)

Q[('0107', 0)] = 10
Q[('0107', 1)] = 11

Q[('1110', 0)] = 1
Q[('1110', 1)] = 2

Q[('1117', 0)] = 3
Q[('1117', 1)] = 4

Q[('0000', 0)] = 5
Q[('0000', 1)] = 6

Q[('0007', 0)] = 7
Q[('0007', 1)] = 8

nbCh = 2

def draw_proba(Q, S, beta=8):
    # draw an action according according
    # to the softmax policy
    r = np.random.random()

    Z = sum(np.exp(beta*Q[(S, a)]) for a in range(nbCh))
    cum_probas = np.zeros(nbCh+1)
    cum_probas[1:] = np.array([np.exp(beta*Q[(S, a)])/Z for a in range(nbCh)]).cumsum()
    
    print(cum_probas)
    for i in range(nbCh+1):
        if cum_probas[i] < r <= cum_probas[i+1]:
            return i

draw_proba(Q, '0000')

[  0.00000000e+00   3.35350130e-04   1.00000000e+00]


1